version: "3.9"
services:
  db:
    container_name: numerology_db
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Long@123
      MYSQL_DATABASE: numerology
    volumes:
      - db_vol:/my/own/datadir

volumes:
  db_vol: